# Site settings
title: Nomad UX Lab
email: hi@nomaduxlab.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/nomaduxlab" # the subpath of your site, e.g. /blog/
url: "https://gyrostu.github.io" # the base hostname & protocol for your site
twitter_username: nomaduxlab
github_username:  gyrostu

# Build settings
markdown: kramdown
